name: onepiece_app
description: "Una aplicacion novedosa para hacer mazos de one piece tcg."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  pdf: ^3.10.0
  printing: ^5.11.0
  
  http: ^1.2.2
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.7

  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  firebase_storage: ^12.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/